In [23]:
import pandas as pd 
import numpy as np 
import datetime as dt 
import yfinance as yf
import plotly.graph_objects as go
import matplotlib.pyplot as plt

In [86]:
df=yf.Ticker("NQ=F")
df=df.history(period='max')
df.reset_index(inplace=True)
df.drop(['Dividends','Stock Splits'],axis=1,inplace=True)
df=df[df['Volume']!=0]
df.columns=df.columns.str.lower()
df=df[df['date']>'2023-01-01']
df

                          date      open      high       low     close  volume
5631 2023-01-03 00:00:00-05:00  11122.50  11182.00  10844.75  10945.50  657681
5632 2023-01-04 00:00:00-05:00  10941.25  11068.50  10863.50  10999.25  758003
5633 2023-01-05 00:00:00-05:00  10988.50  11046.75  10805.00  10820.25  694452
5634 2023-01-06 00:00:00-05:00  10838.75  11165.75  10751.00  11113.50  736332
5635 2023-01-09 00:00:00-05:00  11126.50  11385.50  11120.25  11185.50  646318
...                        ...       ...       ...       ...       ...     ...
5881 2023-12-29 00:00:00-05:00  17090.25  17131.00  16938.25  17023.50  470864
5882 2024-01-02 00:00:00-05:00  17019.00  17038.50  16622.50  16720.00  652714
5883 2024-01-03 00:00:00-05:00  16736.75  16737.25  16522.00  16538.00  677219
5884 2024-01-04 00:00:00-05:00  16545.25  16587.25  16436.00  16445.00  559464
5885 2024-01-05 00:00:00-05:00  16455.00  16577.25  16334.25  16460.25  559464

[255 rows x 6 columns]

In [87]:
def support(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.low.iloc[i] > df1.low.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.low.iloc[i] < df1.low.iloc[i - 1]:
            return 0
    return 1

def resistance(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.high.iloc[i] < df1.high.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.high.iloc[i] > df1.high.iloc[i - 1]:
            return 0
    return 1

sr = []
n1 = 3
n2 = 2

for row in range(n1, 205):
    if support(df, row, n1, n2):
        sr.append((row, df.low.iloc[row], 1))
    if resistance(df, row, n1, n2):
        sr.append((row, df.high.iloc[row], 2))

print(sr)

[(31, 12792.75, 2), (36, 11923.0, 1), (47, 11674.25, 1), (54, 13082.0, 2), (77, 12800.0, 1), (81, 13370.25, 2), (84, 13001.75, 1), (98, 13566.5, 1), (108, 14256.75, 1), (114, 15324.0, 2), (125, 15432.0, 2), (135, 16062.75, 2), (157, 14609.25, 1), (167, 15661.25, 2), (170, 15157.5, 1), (184, 14586.0, 1), (195, 15468.75, 2)]

In [104]:
s=0
e=len(df)
dfpl=df[s:e]
fig=go.Figure(data=[go.Candlestick(x=dfpl.index,
                                  open=dfpl['open'],
                                  close=dfpl['close'],
                                  low=dfpl['low'],
                                  high=dfpl['high'])])
c=0
for line in sr:
    fig.add_shape(type='line', x0=dfpl.index[s], y0=line[1],
                  x1=dfpl.index[e - 1], y1=line[1])
fig.update_layout(title='Us100')
fig.show()

In [97]:
plotlist1=[x[1] for x in sr if x[2]==1]
plotlist2=[x[1] for x in sr if x[2]==2]
plotlist1.sort()
plotlist2.sort()
for i in range(1,len(plotlist1)):
    if(i>=len(plotlist1)):
        break
    if abs(plotlist1[i]-plotlist1[i-1]<=0.005):
        plotlist1.pop(i)
for i in range(1,len(plotlist2)):
    if(i>=len(plotlist2)):
        break
    if abs(plotlist2[i]-plotlist2[i-1]<=0.005):
        plotlist2.pop(i)
s=0
e=len(df)
dfpl=df[s:e]
fig=go.Figure(data=[go.Candlestick(x=dfpl.index,
                                  open=dfpl['open'],
                                  close=dfpl['close'],
                                  low=dfpl['low'],
                                  high=dfpl['high'])])
c=0
while (1):
    if (c>len(plotlist1)-1):
        break
    fig.add_shape(type='line',x0=s,y0=plotlist1[c],
                 x1=e,
                 y1=plotlist1[c],
                 line=dict(color='MediumPurple',width=1))
    c+=1
while (1):
    if (c>len(plotlist2)-1):
        break
    fig.add_shape(type='line',x0=s,y0=plotlist2[c],
                 x1=e,
                 y1=plotlist2[c],
                 line=dict(color='Blue',width=1))
    c+=1    
fig.show()

In [105]:
df=yf.Ticker("CL=F")
df=df.history(period='max')
df.reset_index(inplace=True)
df.drop(['Dividends','Stock Splits'],axis=1,inplace=True)
df=df[df['Volume']!=0]
df.columns=df.columns.str.lower()
df=df[df['date']>'2023-01-01']

def support(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.low.iloc[i] > df1.low.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.low.iloc[i] < df1.low.iloc[i - 1]:
            return 0
    return 1

def resistance(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.high.iloc[i] < df1.high.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.high.iloc[i] > df1.high.iloc[i - 1]:
            return 0
    return 1

sr = []
n1 = 3
n2 = 2

for row in range(n1, 205):
    if support(df, row, n1, n2):
        sr.append((row, df.low.iloc[row], 1))
    if resistance(df, row, n1, n2):
        sr.append((row, df.high.iloc[row], 2))

print(sr)
s=0
e=len(df)
dfpl=df[s:e]
fig=go.Figure(data=[go.Candlestick(x=dfpl.index,
                                  open=dfpl['open'],
                                  close=dfpl['close'],
                                  low=dfpl['low'],
                                  high=dfpl['high'])])
c=0
for line in sr:
    fig.add_shape(type='line', x0=dfpl.index[s], y0=line[1],
                  x1=dfpl.index[e - 1], y1=line[1])
fig.update_layout(title='Crude OIl')

fig.show()

[(23, 72.25, 1), (28, 80.62000274658203, 2), (63, 81.80999755859375, 2), (83, 63.63999938964844, 1), (87, 73.88999938964844, 2), (115, 72.72000122070312, 2), (130, 77.33000183105469, 2), (155, 78.94999694824219, 1), (160, 77.58999633789062, 1), (177, 93.73999786376953, 2), (190, 81.5, 1), (200, 90.77999877929688, 2), (203, 82.08000183105469, 1)]

In [ ]:
df=yf.Ticker("CL=F")
df=df.history(period='max')
df.reset_index(inplace=True)
df.drop(['Dividends','Stock Splits'],axis=1,inplace=True)
df=df[df['Volume']!=0]
df.columns=df.columns.str.lower()
df=df[df['date']>'2023-01-01']

def support(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.low.iloc[i] > df1.low.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.low.iloc[i] < df1.low.iloc[i - 1]:
            return 0
    return 1

def resistance(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.high.iloc[i] < df1.high.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.high.iloc[i] > df1.high.iloc[i - 1]:
            return 0
    return 1

sr = []
n1 = 3
n2 = 2

for row in range(n1, 205):
    if support(df, row, n1, n2):
        sr.append((row, df.low.iloc[row], 1))
    if resistance(df, row, n1, n2):
        sr.append((row, df.high.iloc[row], 2))

print(sr)
s=0
e=len(df)
dfpl=df[s:e]
fig=go.Figure(data=[go.Candlestick(x=dfpl.index,
                                  open=dfpl['open'],
                                  close=dfpl['close'],
                                  low=dfpl['low'],
                                  high=dfpl['high'])])
c=0
for line in sr:
    fig.add_shape(type='line', x0=dfpl.index[s], y0=line[1],
                  x1=dfpl.index[e - 1], y1=line[1])
fig.update_layout(title='Crude OIl')

fig.show()

In [106]:
df=yf.Ticker("EURUSD=X")
df=df.history(period='max')
df.reset_index(inplace=True)
df.drop(['Dividends','Stock Splits'],axis=1,inplace=True)
df=df[df['Volume']!=0]
df.columns=df.columns.str.lower()
df=df[df['date']>'2023-01-01']

def support(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.low.iloc[i] > df1.low.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.low.iloc[i] < df1.low.iloc[i - 1]:
            return 0
    return 1

def resistance(df1, l, n1, n2):
    for i in range(l - n1 + 1, l + 1):
        if df1.high.iloc[i] < df1.high.iloc[i - 1]:
            return 0
    for i in range(l + 1, l + n2 + 1):
        if df1.high.iloc[i] > df1.high.iloc[i - 1]:
            return 0
    return 1

sr = []
n1 = 3
n2 = 2

for row in range(n1, 205):
    if support(df, row, n1, n2):
        sr.append((row, df.low.iloc[row], 1))
    if resistance(df, row, n1, n2):
        sr.append((row, df.high.iloc[row], 2))

print(sr)
s=0
e=len(df)
dfpl=df[s:e]
fig=go.Figure(data=[go.Candlestick(x=dfpl.index,
                                  open=dfpl['open'],
                                  close=dfpl['close'],
                                  low=dfpl['low'],
                                  high=dfpl['high'])])
c=0
for line in sr:
    fig.add_shape(type='line', x0=dfpl.index[s], y0=line[1],
                  x1=dfpl.index[e - 1], y1=line[1])
fig.update_layout(title='Crude OIl')

fig.show()

IndexError: single positional indexer is out-of-bounds

In [107]:
df=yf.Ticker("EURUSD=X")
df=df.history(period='max')
df.reset_index(inplace=True)
df.drop(['Dividends','Stock Splits'],axis=1,inplace=True)
df=df[df['Volume']!=0]
df.columns=df.columns.str.lower()
df=df[df['date']>'2023-01-01']

In [117]:
df= yf.download('EURUSD=X', start="2023-01-01", end=dt.datetime.today().strftime('%Y-%m-%d'))
df

[*********************100%%**********************]  1 of 1 completed

                Open      High       Low     Close  Adj Close  Volume
Date
2023-01-02  1.070973  1.071237  1.065326  1.070973   1.070973       0
2023-01-03  1.067771  1.068262  1.052155  1.067771   1.067771       0
2023-01-04  1.054685  1.063151  1.054596  1.054685   1.054685       0
2023-01-05  1.060637  1.063264  1.051558  1.060637   1.060637       0
2023-01-06  1.052222  1.062225  1.048526  1.052222   1.052222       0
...              ...       ...       ...       ...        ...     ...
2024-01-01  1.105583  1.105339  1.103997  1.105583   1.105583       0
2024-01-02  1.103875  1.104606  1.094200  1.103875   1.103875       0
2024-01-03  1.094176  1.096700  1.089871  1.094176   1.094176       0
2024-01-04  1.092777  1.097021  1.091703  1.092777   1.092777       0
2024-01-05  1.094739  1.099638  1.087985  1.094739   1.094739       0

[265 rows x 6 columns]